### ISSUE TITLE
Pkg.untag()?

### ISSUE THREAD

**Issue by chkwon** [JuliaLang/PkgDev.jl#39]
Would it be possible to untag? While one needs to be careful about tagging, but sometimes makes mistakes in tagging.

**Comment by wildart** [comment]
It's not a trivial task, because some information is committed to the local METADATA repo when tagging happens. This commit need to be removed along with any file system changes. It could be easy to do if will store METADATA commit OID in the package repository tag. Or, we could search MATADATA commit by added files.

So, due to lack of time, this is not a priority issue, but any PR would be very welcome.

**Comment by tkelman** [comment]
Making a new metadata branch before committing the tag, ref https://github.com/JuliaLang/PkgDev.jl/issues/57, would make this simpler.

**Comment by cortner** [comment]
would it be at all easier to *move* a tag? I.e. if I tag a new version, publish it, then I occasionally need to make a change to the package before the METADATA PR is accepted. It would then be nice to just be able to move the last tag to the last commit and automatically update the PR to METADATA.
