### ISSUE TITLE
Warn package developers to specify version for dependencies

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/PkgDev.jl#53]
I propose we adopt as a standard to specify version for dependencies when publishing a tag for a package.

When publishing, PkgDev should warn pkg developer that there's some package at REQUIRE file without a version tag specified.

https://github.com/JuliaData/CSV.jl/issues/28

**Comment by tkelman** [comment]
Good idea, a warning here would be an effective way of prodding on this. It may lead a lot of people to either be really conservative and add the latest (which may cause more conflicts but would at least be accurate w.r.t. what's been tested), or lazy and put something meaningless like 0.0 to just suppress the warning.

**Comment by aviks** [comment]
This would be good for warning about lower bounds. 

I am not a fan of putting an upper bound by default. I think upper bounds should be used only when necessary.

**Comment by tkelman** [comment]
I think a major upper bound is safer than no upper bound at all. No upper bound says "my code will work with every future version that will ever get released" which is impossible to know a-priori.

**Comment by aviks** [comment]
Well, think about what it means for the package developer and the package ecosystem. 

Putting a upper bound on my package means I will have to test and release a new version of my package for every one of my dependencies that are updated. Practically, that means I won't bother. And it probably won't matter for my package. But it makes the ecosystem unhappy.  

If the majority of packages in the ecosystem enforce upper bounds, and do not update them regularly, it will suppress the versions used across all packages, and quite often lead to infeasible solutions. Particularly if a popular package enforces archaic upper bounds. For example, say Distributions enforces an upper bound on an older version of StatFuns. Given how central Distributions is on the dependency graph, it will be well nigh impossible for any other package to use a newer version of StatFuns. Which may be fine in isolation, but multiplied across 1200 packages, it is a recipe for disaster, IMO. 

Because of this I would personally never put an upper bound on a package I maintain. I would rather depend on PkgEval to alert me on any inconsistencies across the "latest released version" of all packages. That is the only "platform" worth supporting, I think.

**Comment by tkelman** [comment]
API breakages happen, and while usually PkgEval can find them fairly quickly, that relies on your package passing its tests there to begin with. People should be thinking about their dependencies in both directions, and when API breaks happen, it's better for users to have bounds than have broken packages.

**Comment by tkelman** [comment]
x-ref the comparable decision that was taken in Rust to ban "wildcard" version requirements https://github.com/rust-lang/rfcs/pull/1241/files

**Comment by tkelman** [comment]
Basically if your package breaks because of too-loose bounds and changing API's in your dependencies, currently *I* will put an upper bound on your package after the fact. I'd rather you pre-emptively save me the work, and prevent the breakage for you and users of your package.

JuliaOpt has been using upper bounds correctly, in that they have to migrate the API of the central MathProgBase package along with other packages that use that API. If they were not careful about upper bounds, then adding new features to JuMP would instantly break every single other JuliaOpt package. Bounds can easily be loosened after-the-fact in METADATA once new versions are released and testing has been done. But it's safer to test first and assert compatibility after those tests have been performed, then assume infinite compatibility in advance and rely on PkgEval or your users to identify a broken configuration being published to METADATA before you find out about incompatibilities.

**Comment by wildart** [comment]
We can suggest exact versions of dependencies based on current state of the dependency cache (e.g. after running tests).

**Comment by tkelman** [comment]
exact is likely to be too conservative, but at least it's accurate w.r.t. what has been locally tested.

**Comment by wildart** [comment]
Unfortunately we do not have version ranges per se (as wildcard or proper range definition) which makes it hard to put an upper bound on dependency version. 

Currently, we can use `lowerbound(nextminor(<dep_version>))` as a default value for dependency and prompt user to correct it if necessary.

**Comment by aviks** [comment]
From the Rust documentation linked above, 
> This RFC originally proposed forbidding all constraints that had no upper
> version bound but has since been pulled back to just `*` constraints.
